title: Consdata - blog techniczny
# the subpath of your site, e.g. /blog
baseurl: ""
# the base hostname & protocol for your site, e.g. http://example.com
url: ""


sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-seo-tag

